### ISSUE TITLE
tokenization error when using msiglip

### ISSUE THREAD

**Issue by simran-khanuja** [google-research/big_vision#126]
Hi, I get this error when preprocessing text using the mSigLIP model. Any idea what may be wrong? I didn't change anything in the [demo colab ](https://colab.research.google.com/github/google-research/big_vision/blob/main/big_vision/configs/proj/image_text/SigLIP_demo.ipynb#scrollTo=KGrpkRTtjU-L)

Traceback (most recent call last):
  File "/home/${USER}/babelnet/labels/msiglip.py", line 131, in <module>
    _, ztxt, out = model.apply({'params': params}, None, txts)
  File "/home/${USER}/babelnet/big_vision/big_vision/models/proj/image_text/two_towers.py", line 55, in __call__
    ztxt, out_txt = text_model(text, **kw)
  File "/home/${USER}/babelnet/big_vision/big_vision/models/proj/image_text/text_transformer.py", line 64, in __call__
    x = out["embedded"] = embedding(text)
  File "/home/${USER}/miniconda3/envs/msiglip/lib/python3.10/site-packages/flax/linen/linear.py", line 1106, in setup
    self.embedding = self.param(
flax.errors.ScopeParamShapeError: Initializer expected to generate shape (256000, 1152) but got shape (250000, 1152) instead for parameter "embedding" in "/txt/Embed_0". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamShapeError)

**Comment by merveenoyan** [comment]
@simran-khanuja I came across the same error, I  have checked the model tree and saw it indeed expects vocab dim of embeddings to be 256k. Can you set it to `256_000` and try again? (in the config)

**Comment by merveenoyan** [comment]
@simran-khanuja not very sure but I came across above issue with the latest released SigLIP (so400m patch16) and the tokenizer is different. Maybe try a different tokenizer, MSigLIP tokenizer spiece model exists [here](https://huggingface.co/google/siglip-base-patch16-256-multilingual/blob/main/spiece.model). 
Also if you're ok with using PyTorch mSigLIP is implemented at transformers, you can use that for time being [here](https://huggingface.co/google/siglip-base-patch16-256-multilingual).
